# Copy from https://github.com/bcoe/nyc/blob/master/appveyor.yml

environment:
  matrix:
    - nodejs_version: '6'
    - nodejs_version: '7'
    - nodejs_version: '8'
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - npm run vscode:postinstall
  - npm run build

matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - node --version
  - npm --version
  - npm test
