export default {
  rootPath: '项目根目录',
  npmPath: '项目的 node_modules 目录',
  date: '当前日期',
  time: '当前时间',
  datetime: '当前日期和当前时间的组合',
  user: '当前用户名称，取的是环境变量中的 USER 字段',
  pkg: '当前 package.json 的 JSON 内容',
  fileName: '当前文件名称，包含路径',
  dirName: '当前文件的路径',
  extension: '当前文件的后缀',
  baseName: '当前文件的基本名称',
  rawModuleName: '当前文件的基本名称',
  moduleName: '驼峰形式的 baseName',
  ModuleName: '单词首字母都大写的形式的 baseName',
  MODULE_NAME: '所有字母都大写，中间以下划线连接的 baseName',
  module_name: '所以字母都小写，中间以下划线连接的 baseName',
}
